apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appcomptes
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
      - name: appcomptes
        image: appcomtes:latest 
        - containerPort: 80 
